import express from "express";
import { createRoom, deleteRoom, GetALLRoom, GetRoom, updateRoom, updateRoomAvailability } from "../controllers/room.js";
import { verifyAdmin } from "../utils/verifyToken.js";
const router=express.Router();
router.post("/:hotelid", verifyAdmin,  createRoom);
router.put("/:id",verifyAdmin,  updateRoom);
router.put("/availability/:id",  updateRoomAvailability);
router.delete("/:id/:hotelid",verifyAdmin, deleteRoom);
router.get("/:id",GetRoom);
router.get("/",GetALLRoom);
export default router;